# Generated by Django 5.2.17 on 2026-10-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('published_on', models.DateField()),
                ('article_url', models.URLField(blank=True, help_text='Optional link to the full note.')),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', '-published_on'),
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('publication', models.CharField(max_length=80)),
                ('published_on', models.DateField()),
                ('category', models.CharField(choices=[('investigations', 'Investigation'), ('features', 'Feature')], max_length=20)),
                ('artwork', models.CharField(choices=[('housing', 'Housing'), ('water', 'Water'), ('school', 'School')], default='housing', max_length=20)),
                ('deck', models.TextField()),
                ('article_url', models.URLField(blank=True, help_text='Optional link to the published article.')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', '-published_on'),
            },
        ),
    ]
