# Generated by Django 5.2.17 on 2026-10-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_seed_initial_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('contact', 'Contact'), ('tip', 'Confidential tip')], max_length=12)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField(max_length=5000)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('is_read', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Kandace Biaz', max_length=100)),
                ('role', models.CharField(default='Independent investigative reporting', max_length=120)),
                ('hero_headline', models.CharField(default='Follow the', max_length=100)),
                ('hero_emphasis', models.CharField(default='paper trail.', max_length=100)),
                ('intro', models.TextField(default='Kandace Biaz reports on the systems that shape daily life: housing, public money, environmental risk, and the people pushing for answers.')),
                ('about_heading', models.CharField(default='Reporting with care, rigor, and a little persistence.', max_length=160)),
                ('bio', models.TextField(default='I am an independent journalist based in the Midwest, where I report long-form investigations and narrative features. My work has prompted public hearings, policy changes, and, most importantly, conversations that otherwise might not have happened.\n\nI believe the best investigations make complicated systems legible — without losing sight of the people living inside them.')),
                ('location', models.CharField(default='Chicago, IL', max_length=100)),
                ('beats', models.CharField(default='Housing · Climate · Power', max_length=180)),
                ('contact_email', models.EmailField(default='hello@kandacebiaz.com', max_length=254)),
                ('tip_email', models.EmailField(default='tips@kandacebiaz.com', max_length=254)),
                ('footer_tagline', models.CharField(default='Independent journalism for the public interest.', max_length=180)),
                ('headshot', models.ImageField(blank=True, upload_to='headshots/')),
            ],
            options={
                'verbose_name': 'site profile',
                'verbose_name_plural': 'site profile',
            },
        ),
    ]
