# Generated by Django 5.2.17 on 2026-10-02 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_seed_site_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='article_body',
            field=models.TextField(blank=True, help_text='Optional full article text. Paragraph breaks are preserved on the public reading page.'),
        ),
        migrations.AddField(
            model_name='story',
            name='article_file',
            field=models.FileField(blank=True, help_text='Optional PDF, Word document, or plain-text version of the article.', upload_to='articles/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'txt'])]),
        ),
        migrations.AlterField(
            model_name='story',
            name='article_url',
            field=models.URLField(blank=True, help_text='Optional link to the published article at its original publication.'),
        ),
    ]
