# Generated by Django 5.2.17 on 2026-10-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_story_article_body_story_article_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='theme',
            field=models.CharField(choices=[('original', 'Original — Paper Trail'), ('harbor', 'Harbor Editorial — Navy & Ivory')], default='original', help_text='Choose the public website style. Save, then refresh the website to compare.', max_length=20),
        ),
    ]
