# Generated by Django 5.2.17 on 2026-10-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_siteprofile_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='theme',
            field=models.CharField(choices=[('original', 'Original — Paper Trail'), ('harbor', 'Harbor Editorial — Navy & Ivory'), ('rose', 'Harbor Rose — Plum & Ivory')], default='original', help_text='Choose the public website style. Save, then refresh the website to compare.', max_length=20),
        ),
    ]
