# Generated by Django 5.2.17 on 2026-10-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_correct_profile_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='intro',
            field=models.TextField(default='Kandace Baez reports on the systems that shape daily life: housing, public money, environmental risk, and the people pushing for answers.'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='name',
            field=models.CharField(default='Kandace Baez', max_length=100),
        ),
    ]
