# Generated by Django 5.2.17 on 2026-10-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_siteprofile_intro_alter_siteprofile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorkboardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField(blank=True, help_text='Public-facing description only. Keep confidential research outside this board.')),
                ('source_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('exploring', 'Exploring'), ('requested', 'Records requested'), ('reviewing', 'Reviewing records'), ('published', 'Published')], default='exploring', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='logo',
            field=models.ImageField(blank=True, help_text='Optional custom logo; otherwise a KB monogram is used.', upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='publication_archive_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='publication_credit',
            field=models.CharField(blank=True, default='Work published in the Navajo-Hopi Observer', max_length=180),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='show_corkboard',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='show_field_notes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='show_logo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='show_support',
            field=models.BooleanField(default=False, help_text='The button appears only when enabled and a payment link is supplied.'),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='support_label',
            field=models.CharField(default='Buy me cat treats', max_length=80),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='support_url',
            field=models.URLField(blank=True, help_text='Paste her chosen hosted donation/payment page URL.'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='theme',
            field=models.CharField(choices=[('original', 'Original — Paper Trail'), ('harbor', 'Harbor Editorial — Navy & Ivory'), ('rose', 'Harbor Rose — Plum & Ivory'), ('midnight', 'Midnight — Deep Blue & White')], default='original', help_text='Choose the public website style. Save, then refresh the website to compare.', max_length=20),
        ),
        migrations.AlterField(
            model_name='story',
            name='published_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
