# Generated by Django 5.2.17 on 2026-10-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_corkboarditem_siteprofile_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, upload_to='story-images/'),
        ),
        migrations.AddField(
            model_name='story',
            name='topic',
            field=models.CharField(blank=True, choices=[('animals', 'Animal rights'), ('mysteries', 'UFOs & unexplained mysteries'), ('nature', 'Wildlife & medicinal plants')], max_length=30),
        ),
    ]
