# Generated by Django 5.2.17 on 2026-10-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_story_image_story_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='artwork',
            field=models.CharField(choices=[('housing', 'Housing'), ('water', 'Water'), ('school', 'School'), ('night', 'Night sky')], default='housing', max_length=20),
        ),
    ]
