# Generated by Django 5.2.17 on 2026-10-04 19:18

from django.db import migrations, models


def enable_support(apps, schema_editor):
    apps.get_model('portfolio', 'SiteProfile').objects.update(show_support=True, support_label='Buy me a dog treat', show_corkboard=False)


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_story_artwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='show_support',
            field=models.BooleanField(default=True, help_text='Show reader support. Without a payment URL the button is a disabled preview.'),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='support_label',
            field=models.CharField(default='Buy me a dog treat', max_length=80),
        ),
        migrations.RunPython(enable_support, migrations.RunPython.noop),
    ]
