# Generated by Django 5.2.17 on 2026-10-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_siteprofile_show_support_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='hero_art',
            field=models.CharField(choices=[('lighthouse', 'Lighthouse'), ('corkboard', 'Corkboard')], default='lighthouse', max_length=20),
        ),
    ]
