# Generated by Django 5.2.17 on 2026-10-04 19:39

from django.db import migrations, models


def correct_support_label(apps, schema_editor):
    apps.get_model('portfolio', 'SiteProfile').objects.filter(support_label='Buy me a dog treat').update(support_label='Buy me cat treats')


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_siteprofile_hero_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='support_label',
            field=models.CharField(default='Buy me cat treats', max_length=80),
        ),
        migrations.RunPython(correct_support_label, migrations.RunPython.noop),
    ]
