# Generated by Django 5.2.17 on 2026-10-04 19:48

from django.db import migrations, models


def preview_glow(apps, schema_editor):
    apps.get_model('portfolio', 'SiteProfile').objects.filter(theme='midnight').update(theme='glow')


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_alter_siteprofile_support_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='theme',
            field=models.CharField(choices=[('original', 'Original — Paper Trail'), ('harbor', 'Harbor Editorial — Navy & Ivory'), ('rose', 'Harbor Rose — Plum & Ivory'), ('midnight', 'Midnight — Deep Blue & White'), ('glow', 'Midnight Glow — Soft Navy Gradient')], default='original', help_text='Choose the public website style. Save, then refresh the website to compare.', max_length=20),
        ),
        migrations.RunPython(preview_glow, migrations.RunPython.noop),
    ]
