# Generated by Django 5.2.17 on 2026-10-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_alter_siteprofile_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='logo_style',
            field=models.CharField(choices=[('cat', 'Cat — Curious Observer'), ('lighthouse', 'Lighthouse — Clear Signal'), ('pen', 'Pen & Star — Independent Voice')], default='cat', max_length=20),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='logo',
            field=models.ImageField(blank=True, help_text='Optional custom logo; otherwise the selected illustrated logo is used.', upload_to='logos/'),
        ),
    ]
