# Generated by Django 5.2.17 on 2026-10-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_siteprofile_logo_style_alter_siteprofile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='pin_nav',
            field=models.BooleanField(default=False, help_text='Keep the navigation at the top while scrolling.'),
        ),
    ]
