# Generated by Django 5.2.17 on 2026-10-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_siteprofile_pin_nav'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='favorite_quote_one',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='favorite_quote_one_author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='favorite_quote_two',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='favorite_quote_two_author',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
