# Generated by Django 5.2.17 on 2026-10-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_siteprofile_favorite_quote_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='hero_art',
            field=models.CharField(choices=[('lighthouse', 'Lighthouse'), ('corkboard', 'Corkboard'), ('portrait', 'Kandace & cat')], default='lighthouse', max_length=20),
        ),
    ]
