# Generated by Django 5.2.17 on 2026-10-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_alter_siteprofile_hero_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='hero_art',
            field=models.CharField(choices=[('lighthouse', 'Lighthouse'), ('corkboard', 'Corkboard'), ('portrait', 'Kandace & cat'), ('observer', 'Observer photo'), ('poolcat', 'Pool-table cat')], default='lighthouse', max_length=20),
        ),
    ]
